### ISSUE TITLE
civicpy: pickle data truncated

### ISSUE THREAD

**Issue by HomoPolyethylen** [qbic-pipelines/variantmtb#17]
### Description of the bug

Sometimes this error occurs.

Maybe the following line is the problem?
https://github.com/qbic-pipelines/variantmtb/blob/51296968d38a94924c02ab86249a8f54a13e661b/modules/local/querynator/civicapi.nf#L37

the line sets the civicpy cache in the workdir, so all processes use the same cache file. Parallel processes might try to read/update it simultaneously, causing the error?
--> single sample run should then work
--> removed cache, ran single sample, failed with same err

### Command used and terminal output

```console
2024-09-28 15:04:17,869 - Querynator - INFO - Start
  2024-09-28 15:04:17,895 - Querynator - INFO - Unzipping input file (GENIE-MSK-P-0009822-T01-IM5.normalized.vcf.gz)
  2024-09-28 15:04:17,899 - Querynator - INFO - Filtering vcf file
  2024-09-28 15:04:17,901 - Querynator - INFO - Query the Clinical Interpretations of Variants In Cancer (CIViC)
  2024-09-28 15:04:17,901 - Querynator - INFO - Updating CIViCpy Cache
  Traceback (most recent call last):
    File "/usr/local/bin/querynator", line 10, in <module>
      sys.exit(run_querynator())
    File "/usr/local/lib/python3.10/site-packages/querynator/__main__.py", line 278, in run_querynator
      querynator_cli()
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/querynator/__main__.py", line 450, in query_api_civic
      query_civic(candidate_variants, result_dir, logger, vcf, genome, cancer, filter_vep)
    File "/usr/local/lib/python3.10/site-packages/querynator/query_api/civic_api.py", line 645, in query_civic
      civic.load_cache()
    File "/usr/local/lib/python3.10/site-packages/civicpy/civic.py", line 196, in load_cache
      loaded_cache = pickle.load(pf)
  _pickle.UnpicklingError: pickle data was truncated
```

**Comment by HomoPolyethylen** [comment]
querynator tests for civic now fail -> seems like a civicpy server-side issue and out of my hands :(

**Comment by HomoPolyethylen** [comment]
fixed by civicpy
